[package]
name = "pyatexit"
version = "0.1.0"
edition = "2021"

[dependencies]
cpython_ext = { path = "../../../../lib/cpython-ext" }
atexit = { path = "../../../../lib/util/atexit" }
cpython = { version = "0.7", default-features = false }
